GTU:
	gcc -o wholesaler wholesaler.c -lrt -pthread -Wall
	gcc -o hw3named hw3named.c -lrt -pthread -Wall
	gcc -o pusher1 pusher1.c -lrt -pthread -Wall
	gcc -o pusher2 pusher2.c -lrt -pthread -Wall
	gcc -o pusher3 pusher3.c -lrt -pthread -Wall
	gcc -o pusher4 pusher4.c -lrt -pthread -Wall
	gcc -o generic_chef generic_chef.c -lrt -pthread -Wall